stock_view_backend/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from stock_view_backend_app import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^api/', include('stock_view_backend_app.urls')),
    url(r'^admin/', admin.site.urls),
]

stock_view_backend_app/urls.py
from django.conf.urls import url
from stock_view_backend_app import views

# Template Tagging
app_name = 'stock_view_backend_app'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^help', views.help, name='help'),
	url(r'^access', views.access, name='access'),
	url(r'^users', views.users, name='users'),
	url(r'^formpage', views.form_name_view, name='form_name'),
	url(r'^other', views.other, name='other'),
	url(r'^relative', views.relative, name='relative'),
	url(r'^register', views.register, name='register'),
	url(r'^logout', views.user_logout, name='logout'),
	url(r'^user_login', views.user_login, name='user_login'),
	url(r'^CBView', views.CBView.as_view(), name='CBView'),
	url(r'^IndexView', views.IndexView.as_view(), name='IndexView'),
	url(r'^list', views.SchoolListView.as_view(), name='list'),
	url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
	url(r'^create', views.SchoolCreateView.as_view(), name='create'),
	url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
	url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

stock_view_backend_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse

class School(models.Model):
	name = models.CharField(max_length=264)
	principal = models.CharField(max_length=264)
	location = models.CharField(max_length=264)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("stock_view_backend_app:detail", kwargs={'pk':self.pk})

class Student(models.Model):
	name = models.CharField(max_length=264)
	age = models.PositiveIntegerField()
	school = models.ForeignKey(School, related_name='students')
	
	def __str__(self):
		return self.name
		


class Topic(models.Model):
	top_name = models.CharField(max_length=264, unique=True)

	def __str__(self):
		return self.top_name

class Webpage(models.Model):
	topic = models.ForeignKey(Topic)
	name = models.CharField(max_length=264, unique=True)
	url = models.URLField(unique=True)

	def __str__(self):
		return self.name

class AccessRecord(models.Model):
	name = models.ForeignKey(Webpage)
	date = models.DateField()

	def __str__(self):
		return str(self.date)

class UserModel(models.Model):
	first_name = models.CharField(max_length=264)
	last_name = models.CharField(max_length=264)
	email = models.EmailField(max_length=264, unique=True)

	def __str__(self):
		return self.first_name+" "+self.last_name

class UserProfileInfo(models.Model):

	# Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    profile_pic = models.ImageField(upload_to='basic_app/profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	create_date = models.DateTimeField(default=timezone.now())
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def approve_comments(self):
		return self.comments.filter(approve_comment=True)

	def get_absolute_url(self):
		return reverse("stock_view_backend_app:post_detail", kwargs={'pk':self.pk})
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	post = models.ForeignKey('blog.Post', related_name='comments')
	author = models.CharField(max_length=200)
	text = models.TextField()
	create_date = models.DateTimeField(default=timezone.now())
	approve_comment = models.BooleanField(default=False)

	def approve(self):
		self.approve_comment=True
		self.save()

	def get_absolute_url(self):
		return reverse("stock_view_backend_app:post_list")
	
	def __str__(self):

stock_view_backend_app/forms.py
from django import forms
from django.core import validators
from stock_view_backend_app.models import UserModel, UserProfileInfo, Post, Comment
from django.contrib.auth.models import User

# def check_for_z(value):
# 	if value[0].lower() != 'z':
# 		raise forms.ValidationError("The value for the name field input needs to start with the character z!")

class FormName(forms.Form):
	# name = forms.CharField(validators=[check_for_z])
	name = forms.CharField()
	email = forms.EmailField()
	verify_email = forms.EmailField(label='Enter your email again:')
	text = forms.CharField(widget=forms.Textarea)

	def clean(self):
		all_clean_data = super().clean()
		email = all_clean_data['email']
		vmail = all_clean_data['verify_email']

		if email != vmail:
			raise forms.ValidationError("Make sure emails match!")

	# botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

	# def clean_botcatcher(self):
	# 	botcatcher = self.cleaned_data['botcatcher']
	# 	if len(botcatcher) > 0:
	# 		raise forms.ValidationError("GOTCHA BOT!")
	# 	return botcatcher

class NewUserForm(forms.ModelForm):
	class Meta():
		model = UserModel
		fields = '__all__'

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta(object):
		model = User
		fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta(object):
		model = UserProfileInfo
		fields = ('portfolio_site', 'profile_pic')

class PostForm(forms.ModelForm):
	class Meta():
		model = Post
		fields = ('author', 'title', 'text')

		widget = {
			'title': forms.TextInput(attrs={'class':'textinputclass'})
			'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
		}

class CommentForm(forms.ModelForm):
	class Meta():
		model = Comment
		fields = ('author', 'text')

		widget = {
			'author': forms.TextInput(attrs={'class':'textinputclass'})
			'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
		}

stock_view_backend_app/views.py
from django.shortcuts import render
from . import forms, models
from stock_view_backend_app.models import AccessRecord,Webpage,Topic
from stock_view_backend_app.forms import NewUserForm, UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from django.views.generic import (View, TemplateView, 
                                ListView, DetailView,
                                CreateView, UpdateView,
                                DeleteView)

# Create your views here.

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'stock_view_backend_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("stock_view_backend_app:list")


class IndexView(TemplateView):
    template_name = 'stock_view_backend_app/index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'Basic Injection!'
        return context

class CBView(View):
    def get(self, request):
        return HttpResponse("Class based Views Are Neet!")


def index(request):
	context_dict = {'text':'Hello world!', 'number':100}
	return render(request, 'stock_view_backend_app/index.html',context_dict)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def help(request):
	my_dict = {'insert_me': "Hello I am from stock_view_backend_app/views.py !"}
	return render(request, 'stock_view_backend_app/help.html', context=my_dict)

def access(request):
	webpages_list = AccessRecord.objects.order_by('date')
	date_dict = {'access_records': webpages_list}
	return render(request, 'stock_view_backend_app/access.html', context=date_dict)

def users(request):
	form = NewUserForm()
	if request.method == "POST":
		form = NewUserForm(request.POST)

		if form.is_valid():
			form.save(commit=True)
			return index(request)
		else:
			print("ERROR: Form Invalid!")

	return render(request, 'stock_view_backend_app/users.html', {'form': form})

def form_name_view(request):
	form = forms.FormName()

	if request.method == 'POST':
		form = forms.FormName(request.POST)

		if form.is_valid():
			print("VALIDATION SUCCESS!")
			print("NAME: "+form.cleaned_data['name'])
			print("EMAIL: "+form.cleaned_data['email'])
			print("TEXT: "+form.cleaned_data['text'])

	return render(request, 'stock_view_backend_app/form_page.html', {'form':form})

def other(request):
	return render(request, 'stock_view_backend_app/other.html')

def relative(request):
	return render(request, 'stock_view_backend_app/relative_url_templates.html')

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'stock_view_backend_app/registration.html', {'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("LOGIN FAILED")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("invalidlogin details supplied!")

    else:
        return render(request, 'stock_view_backend_app/login.html', {})

templates/stock_view_backend_app/access.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
		<title>StockView Backend</title>
		<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	</head>
	<body>
		<h1>Django rec</h1>
		<h2>Access Records:</h2>
		<div class="djangtwo">
			{% if access_records %}
				<table>
					<thead>
						<th>Site Name</th>
						<th>Date Accessed</th>
					</thead>

					{% for acc in access_records %}
					<tr>
						<td>{{ acc.name }}</td>
						<td>{{ acc.date }}</td>
					</tr>
					{% endfor %}
				</table>
			{% else %}
				<p>NO ACCESS RECORDS FOUND!</p>
			{% endif %}

		</div>
	</body>
</html>

templates/stock_view_backend_app/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<ul class="nav navbar-nav">
					<li><a class="navbar-brand" href="{% url 'stock_view_backend_app:index' %}">Brand</a></li>
					<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
					<li><a class="navbar-link" href="{% url 'stock_view_backend_app:list' %}">Schools</a></li>
					<li><a class="navbar-link" href="{% url 'stock_view_backend_app:register' %}">Register</a></li>
					{% if user.is_authenticated %}
					<li><a class="navbar-link" href="{% url 'stock_view_backend_app:logout' %}">Logout</a></li>
					{% else %}
					<li><a class="navbar-link" href="{% url 'stock_view_backend_app:user_login' %}">Login</a></li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="container">
			{% block body_block %}
			<!-- Anything outside of this will be inherited if you extend! -->
			{% endblock %}
		</div>
	</body>
</html>

templates/stock_view_backend_app/form_page.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Forms</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	</head>
	<body>
		<h1>Fill Form!</h1>
		<div class="container">
			<form method="POST">
					{{form.as_p}}
					{% csrf_token %}
				<input type="submit" class="btn btn-primary" value="Submit">
			</form>
		</div>
	</body>
</html>

templates/stock_view_backend_app/help.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
		<title>Help</title>
		<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	</head>
	<body>
		<h1>Recycle</h1>
		<img src="{% static "images/rec.jpg" %}" alt="rec image">
		<h1>Help Page!</h1>
		{{ insert_me }}
	</body>
</html>

templates/stock_view_backend_app/index.html
<!DOCTYPE html>
{% extends "stock_view_backend_app/base.html" %}
{% load my_extras %}
{% block body_block %}
<div class="jumbotron">
	<h1>Index</h1>
	<h1>{{ text|cut:' world'}}</h1>
	<h1>{{ number|add:"99" }}</h1>
	<h2>Injected Content: {{ injectme }}</h2>
</div>
{% endblock %}

templates/stock_view_backend_app/login.html
<!DOCTYPE html>
{% extends "stock_view_backend_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
	<h1>Login</h1>
	<form action="{% url 'stock_view_backend_app:user_login'%}" method="post">
		{% csrf_token %}
		<label for="username">Username:</label>
		<input type="text" name="username" placeholder="Enter Username">

		<label for="password">Password:</label>
		<input type="password" name="password">

		<input type="submit" value="Login">
	</form>
</div>
{% endblock %}

templates/stock_view_backend_app/old_registration.html
{% extends "stock_view_backend_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

templates/stock_view_backend_app/other.html
<!DOCTYPE html>
{% extends "stock_view_backend_app/base.html" %}
{% block body_block %}
	<h1>Other</h1>
	<h2>This is an example of template inheritance!</h2>
{% endblock %}

templates/stock_view_backend_app/registration.html
{% extends "stock_view_backend_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

templates/stock_view_backend_app/relative_url_templates.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Relative URL Templates</title>
	</head>
	<body>
		<h1>Relative URL Templates</h1>
		<a href="{% url 'stock_view_backend_app:other' %}">The Other Page</a>
		<a href="{% url 'admin:index' %}">Link To Admin</a>
		<a href="{% url 'index' %}">Link To Index</a>
	</body>
</html>

templates/stock_view_backend_app/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
	<head>
		<meta charset="utf-8">
		<title>Users</title>
		<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	</head>
	<body>
		<div class="container">
			<h1>Sign Up</h1>
			<form method="POST">
				{{ form.as_p }}
				{% csrf_token %}
				<input type="submit" class="btn btn-primary" value="Submit">
			</form>

		</div>
	</body>
</html>